plugins {
    id('net.fabricmc.fabric-loom') version('1.15-SNAPSHOT') apply false
    id("net.neoforged.moddev") version("2.0.141") apply(false)
    id("idea")
}

subprojects {
    repositories {
        maven {
            name = "Valhelsia Core"
            url = uri("https://maven.pkg.github.com/ValhelsiaTeam/Valhelsia-Core")
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: findProperty("gpr.user")
                password = System.getenv("GITHUB_TOKEN") ?: findProperty("gpr.key")
            }
        }
    }
}