org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

archives_base_name=valhelsia_furniture
maven_group=net.valhelsia

architectury_version=${ARCHITECTURY_API_VERSION}

fabric_loader_version=0.18.2
fabric_api_version=0.139.4+1.21.11

## Environment Properties

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)
neo_version=21.11.3-beta
neo_version_range=[21.11,)
loader_version_range=[4,)

valhelsia_core_version=1.1.5
dataforge_version=1.21.11-0.1.0

parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

## Mod Properties

mod_id=valhelsia_furniture
mod_name=Valhelsia Furniture
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=net.valhelsia
mod_authors=Khytwel, stal111, Vaelzan
mod_description=
