plugins {
    id("net.neoforged.moddev")
}

sourceSets {
    main {
        resources {
            srcDir '../datagen/src/generated/resources'
        }
    }
}

neoForge {
    neoFormVersion = "1.21.11-20251209.172050"

    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = parchment_minecraft_version
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation "net.valhelsia:valhelsia_core-common-${minecraft_version}:${valhelsia_core_version}"
}
