plugins {
    id 'net.neoforged.moddev' version '2.0.107'
}

sourceSets {
    main {
        resources {
            srcDir '../datagen/src/generated/resources'
        }
    }
}

neoForge {
    neoFormVersion = "1.21.8-20250717.133445"

    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = parchment_minecraft_version
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation "net.valhelsia:valhelsia_core-common-${minecraft_version}:${valhelsia_core_version}"
}
